temperature_tracker:
  ros__parameters:
    publish_gpu_temperature: True  #if using non nvidia GPU set this to false
    publish_cpu_temperature: True
    cpu_type_id: "x86_pkg_temp" #dependent on CPU architecture, see readme
    gpu_output_topic: "gpu_temperature"
    cpu_output_topic: "cpu_temperature"
    publish_rate: 1   #publish rate in seconds